title: Amrutha Vinayakam
logo: https://amruthavinayakam.github.io/assets/picture.png
description: Graduate Teaching Assistant | Graduate Technical Assistant | AI Engineer
# show_downloads: False
theme: jekyll-theme-minimal
